"""
Pytest configuration and fixtures for agenda-engine tests.
"""

import sys
from pathlib import Path

# Add src to path
src_path = Path(__file__).parent.parent / "src"
sys.path.insert(0, str(src_path))

# Add agents to path  
agents_path = Path(__file__).parent.parent.parent.parent / "agents"
sys.path.insert(0, str(agents_path))

import pytest
from unittest.mock import MagicMock, AsyncMock


@pytest.fixture
def mock_database():
    """Mock database connection."""
    mock = MagicMock()
    mock.connection = MagicMock()
    return mock


@pytest.fixture
def mock_llm_client():
    """Mock LLM client for testing."""
    mock = AsyncMock()
    mock.generate = AsyncMock(return_value="Test content generated by LLM")
    return mock
