import {
  Activity,
  ArrowDown,
  ArrowRight,
  Award,
  BarChart3,
  Bell,
  Bookmark,
  Bot,
  Box,
  Brain,
  Calendar,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleOff,
  Clock,
  Code,
  Coffee,
  Cog,
  Copy,
  Cpu,
  Database,
  Dice5,
  Dribbble,
  Eye,
  Film,
  Globe,
  Heart,
  HeartPulse,
  Info,
  Landmark,
  Lightbulb,
  Loader2,
  Menu,
  MessageCircle,
  MessageSquare,
  Moon,
  Palette,
  Plus,
  Radio,
  RefreshCw,
  Search,
  Settings,
  Smile,
  Sparkles,
  Sun,
  Terminal,
  TrendingUp,
  Trophy,
  Tv,
  User,
  UserCog,
  UserPlus,
  Users,
  X,
  Zap,
  ZapOff,
} from "lucide-angular";
import {
  bootstrapApplication,
  provideProtractorTestingSupport,
} from "@angular/platform-browser";
import { provideHttpClient, withInterceptors } from "@angular/common/http";

import { AppComponent } from "./app/app.component";
import { LucideAngularModule } from "lucide-angular";
import { apiResponseInterceptor } from "./app/core/interceptors/api-response.interceptor";
import { importProvidersFrom } from "@angular/core";
import { provideRouter } from "@angular/router";
import { routes } from "./app/app.routes";

bootstrapApplication(AppComponent, {
  providers: [
    provideRouter(routes),
    provideHttpClient(withInterceptors([apiResponseInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({
        Activity,
        Radio,
        Trophy,
        Zap,
        TrendingUp,
        Dribbble,
        Film,
        Box,
        Bot,
        BarChart3,
        Settings,
        Bell,
        Search,
        Menu,
        User,
        Users,
        UserPlus,
        UserCog,
        Clock,
        Eye,
        Bookmark,
        ChevronRight,
        ChevronUp,
        ChevronDown,
        Sun,
        Coffee,
        Tv,
        Moon,
        X,
        Calendar,
        Award,
        ArrowRight,
        Loader2,
        Database,
        Info,
        Copy,
        Check,
        Globe,
        Palette,
        Sparkles,
        HeartPulse,
        Cpu,
        Landmark,
        MessageCircle,
        MessageSquare,
        ZapOff,
        Brain,
        Smile,
        Terminal,
        Cog,
        ArrowDown,
        CircleOff,
        Heart,
        Lightbulb,
        Dice5,
        RefreshCw,
        Code,
        Plus,
      }),
    ),
  ],
}).catch((err) => console.error(err));
